#!/bin/bash

script_name=$(basename "$0")

# Usage
usage() {
    echo "Usage: $script_name workflow-type command"
    echo "           [--input INPUT] [--port PORT] [--namespace NAMESPACE]"
    echo "  start    Start new Workflow"     echo "  list     List most recent Workflows (up to 10)"
    echo "  latest   Latest workflow ID"
    echo "  results  Latest workflow results"
    echo "Description: Create and manage workflows on the Temporal Cloud Server."
    echo "The Workflow ID, Task Queue, and Workflow Type are all set to match the"
    echo "Workflow definition you use. (Tutorials: TutorialWorkflow)"
    exit 1
}

# Start Workflow

run_command_basic() {
    temporal workflow $command \
        --namespace $namespace \
        --address $address \
        --tls-cert-path "$HOME/.ssh/tcloud.pem" \
        --tls-key-path "$HOME/.ssh/tcloud.key" \
	$1
}

run_command_withqueue() {
    temporal workflow $command \
        --task-queue $task_queue \
        --type $workflow_type \
        --workflow-id $workflow_id \
        --namespace $namespace \
        --address $address \
        --input $input \
        --tls-cert-path "$HOME/.ssh/tcloud.pem" \
        --tls-key-path "$HOME/.ssh/tcloud.key"
}



# Parse flags

input='null'
port="7233"
namespace="docs-assembly.a2dd6"

if [ "$#" -lt 2 ]; then
    usage
fi

workflow_type="$1"
command="$2"
shift 2

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --input) input="\"$2\""; shift ;;
        --port) port="$2"; shift ;;
        --namespace) namespace="$2"; shift ;;
        *) break ;;
    esac
    shift
done

task_queue="$workflow_type-queue"
address="$namespace.tmprl.cloud:$port"
workflow_id="$workflow_type-$(date +%s)"

case "$command" in

    start)
        run_command_withqueue ;;

    list)  
        run_command_basic "--limit 10 --color never --fields Execution.WorkflowId -o card" ;;

    latest)
        command="list"
        output=$(run_command_basic "--limit 1 --color never --fields Execution.WorkflowId -o card")
        id=$(echo $output |  sed 's/[^0-9]*//g')
        echo "$workflow_type-$id"
        ;;

    results)
        command="list"
        output=$(run_command_basic "--limit 1 --color never --fields Execution.WorkflowId -o card")
        id=$(echo $output |  sed 's/[^0-9]*//g')
        workflow_execution="$workflow_type-$id"
        command="show --workflow-id $workflow_execution"
        details=$(run_command_basic "")
        echo $details | sed 's/.*Output: \[.//' | sed 's/.\]//'
        ;;

    *) usage ;;
esac

exit 0