#!/bin/bash

# Usage
function usage {
    echo "Usage: $(basename "$0") <command> [json|id-number]"
    echo "  start [input]   Start new Workflow."
    echo "  terminate <id>  Terminate a Workflow."
    echo "  running         List active workflows."
    echo "  list            List up to 10 workflows from this server session."
    echo "  killall         Terminate all active Workflows."
    echo "  usage-long      More usage options."
    echo ""
    echo "Description: Create and manage workflows on the Temporal Development Server."
    exit 1
}

function usage-long {
    echo "Usage: $(basename "$0") <command> [json|id-number]"
    echo "  usage-long      This message."
    echo "  latest          Show most recent Workflow."
    echo "  result          Show result of most recent Workflow."
    echo "  runid <id>      Show Workflow run-id."
    echo "  start [input]   Start new Workflow."
    echo "  cancel <id>     Cancel Workflow."
    echo "  cancelit        Cancel most recent Workflow."
    echo "  terminate <id>  Terminate a Workflow."
    echo "  describe <id>   Describe Workflow."
    echo "  describeit      Describe most recent Workflow."
    echo "  show <id>       Show Workflow details."
    echo "  showit          Show details for most recent Workflow."
    echo "  showlong        Show in-depth details for most recent Workflow."
    echo "  list            List up to 10 recent Workflows."
    echo "  running         List active workflows."
    echo "  killall         Terminate all active Workflows."
    echo "  signal          Not yet implemented."
    exit 0
}

# Start a Workflow
function start_workflow {
    local input="${1:-\"Hello World\"}"
    local epoch=$(date +%s)
    local unique_id="TutorialWorkflow.${epoch}"

    if [ "$input" == "ip" ]; then
        input="\"$(curl -s4 ifconfig.co)\""
    elif [ "$input" == "dad" ]; then
        input="\"$(curl -s https://icanhazdadjoke.com/ | \
        sed 's/\\/\\\\/g; s/"/\\"/g; s/$/\\n/' | tr -d '\n')\""
    fi

    echo "Starting workflow with ID: ${unique_id}"
    temporal workflow start \
        --workflow-id "${unique_id}" \
        --type TutorialWorkflow \
        --task-queue TutorialWorkflow-queue \
        --input "${input}"
}

# Requires one command, otherwise show Usage.
if [ $# -lt 1 ]; then usage; fi

# Execute the selected command
case "$1" in
    start) start_workflow "${@:2}" ;;

    usage-long) usage-long;;

    cancel)
        if [ $# -ne 2 ]; then usage; fi
        temporal workflow cancel --workflow-id "TutorialWorkflow-queue.$2"
        ;;

    cancelit)
        temporal workflow cancel --workflow-id `tflow latest` ;;

    describe)
        if [ $# -ne 2 ]; then usage; fi 
        temporal workflow describe --workflow-id "TutorialWorkflow.$2" 
        ;;

    describeit)
        temporal workflow describe --workflow-id `tflow latest` ;;

    latest)
        echo "$(temporal workflow list --limit 1 --color never --fields Execution.WorkflowId -o card | sed 's/.*Execution.WorkflowId.*io/io/')"
	;;

    runid)
        if [ $# -ne 2 ]; then usage; fi 
        echo $(temporal workflow describe --workflow-id "TutorialWorkflow.$2" | jq .workflowExecutionInfo.execution.runId | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g") | awk '{gsub(/\"/, "")}1'
        ;;

    result)
        echo "$(temporal workflow show --workflow-id `tflow latest` | grep Output)"
        ;;

    show) 
        if [ $# -ne 2 ]; then usage; fi
        temporal workflow show --workflow-id "TutorialWorkflow.$2"
        ;;

    showit)
        temporal workflow show --workflow-id `tflow latest` ;;

    showlong)
        temporal workflow show --fields long  --color no --workflow-id `tflow latest` ;;

    running)
        if [[ -z $(temporal workflow list \
              --query="ExecutionStatus = 'Running'") ]]; then
            echo "No active Workflows were found."
        else
            temporal workflow list --query="ExecutionStatus = 'Running'"
        fi
        ;;

    signal)
        echo "Signal functionality not yet implemented." ;; 

    show)
        if [ $# -ne 2 ]; then usage; fi
        temporal workflow show --workflow-id "TutorialWorkflow.$2"
        ;;

    killall)
        temporal workflow list --query="ExecutionStatus = 'Running'" | \
        awk '{ gsub(/[^0-9]/, " "); for(i=1; i<=NF; i++) if(length($i) >= 8) print $i }' | \
        xargs -I {} bash -c ' echo "Terminating workflow TutorialWorkflow.{}" && temporal workflow terminate --workflow-id "TutorialWorkflow.{}"' 
        ;;

    list)
       temporal workflow list --limit 10 ;; 

    terminate)
        if [ $# -ne 2 ]; then usage; fi
        temporal workflow terminate --workflow-id "TutorialWorkflow.$2" 
        ;;

    *) usage ;;

esac

exit 0